-- Category
INSERT INTO INV_CATEGORY (CAT_ABBR, CAT_NAME) VALUES ('MONITOR', 'Monitor, TV, ...');
INSERT INTO INV_CATEGORY (CAT_ABBR, CAT_NAME) VALUES ('CHROMECAST', 'Cromecast-Geräte');
INSERT INTO INV_CATEGORY (CAT_ABBR, CAT_NAME) VALUES ('FOTO', 'Fotoapparate und Zubehör');

-- Device
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR) VALUES (1000, 'IIYAMA', '', '86" Monitor', 'xy-123', null, 'MONITOR');
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR) VALUES (1001, 'Canon', null, 'Fotoapparat-Set', '70D', null, 'FOTO');
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR) VALUES (1003, 'n/a', null, 'Fototasche', 'n/a', 1001, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR) VALUES (1002, 'n/a', null, 'Stativ', 'n/a', 1001, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR) VALUES (1004, 'Canon', null, 'Fotoapparat', '70D', 1001, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR) VALUES (1005, 'Google', null, 'Chromecast 3', 'Chromecast 3', null, 'CHROMECAST');

INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR)
VALUES
    (1006, null, null, null, 'A', null, 'CHROMECAST');
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR)
VALUES
    (1007, null, null, null, 'A.B', 1006, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR)
VALUES
    (1008, null, null, null, 'A.C', 1006, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR)
VALUES
    (1009, null, null, null, 'A.C.D', 1008, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR)
VALUES
    (1010, null, null, null, 'A.C.D.E', 1009, null);
INSERT INTO INV_DEVICE (DEV_ID, DEV_BRAND, DEV_DESCR, DEV_SHORT_NAME, DEV_TYPE, DEV_DEV_ID, DEV_CAT_ABBR)
VALUES
    (1011, null, null, null, 'A.C.D.E.F', 1010, null);


-- Event


